package interfaccia;

public enum ComingTable {

    AUTORE, BIGLIETTO, STAFF, GUIDA, RESTAURATORE, MUSEO, OPERA, PERMANENZA, RESTAURO, SEZIONE, SUPPORTO_GUIDA, SUPPORTO_MULTIMEDIALE, TIPOLOGIA, UTILIZZO_STRUMENTO,
    VISITA_GRUPPO, VISITA_SINGOLA, VISITATORE;
}
